### PR TITLE
- Update HTML / JS / CSS to AdminLTE 2.3.7

### PR DESCRIPTION
**Pull request by texpert**
- Bumped 'bootstrap-sass' gem to 3.3.7 version
- Adding stylesheets correctly for 'sass' or 'scss' engine into the 'application.scss' file
- Fixed iCheck plugin css loading to use '@import url()'
- DRYed generators inheriting from a BaseGenerator
- Added 'font-awesome-rails' gem runtime dependency to DRY the .erb templates

### CODE REVIEW

**Comment by texpert** [comment]
Hello, @purintai !

Forked you repo seeing that it has a fresh AdminLTE and made some additions. Would you be so kind to take a look?

**Comment by purintai** [comment]
Many thanks. But I forked this repository only for my private projects.
Please do not expect it to be maintained in the future. :sweat_smile: 

Thanks. :smile:

**Comment by texpert** [comment]
Would you, then, make a PR to original repo, please?

**Comment by purintai** [comment]
You can also create PR to original repo from [here](https://github.com/nicolas-besnard/adminlte2-rails/compare/master...texpert:master).

BTW, original owner seem to be [preparing for v1.0](https://github.com/nicolas-besnard/adminlte2-rails/commits/v1.0). (but it has not been recently updated)

**Comment by texpert** [comment]
OK, I will create a PR.

Thanks for your work too! :)

**Pull request merged**
